//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessageException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessageException() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("finefin.api.Exceptions.ResourceMessageException", typeof(ResourceMessageException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum description length is 50 characters..
        /// </summary>
        public static string DESCRIPTION_MAX_LENGTH {
            get {
                return ResourceManager.GetString("DESCRIPTION_MAX_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description must have at least 4 characters..
        /// </summary>
        public static string DESCRIPTION_MIN_LENGTH {
            get {
                return ResourceManager.GetString("DESCRIPTION_MIN_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be empty..
        /// </summary>
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An user with this email already exists..
        /// </summary>
        public static string EMAIL_EXISTS {
            get {
                return ResourceManager.GetString("EMAIL_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email invalid..
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name cannot be empty..
        /// </summary>
        public static string FIRSTNAME_EMPTY {
            get {
                return ResourceManager.GetString("FIRSTNAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firts name should have between 2 and 30 characters..
        /// </summary>
        public static string FIRSTNAME_LENGTH {
            get {
                return ResourceManager.GetString("FIRSTNAME_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t complete this operation due to insufficient funds..
        /// </summary>
        public static string INSUFFICIENT_FUNDS {
            get {
                return ResourceManager.GetString("INSUFFICIENT_FUNDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid id..
        /// </summary>
        public static string INVALID_ID {
            get {
                return ResourceManager.GetString("INVALID_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name cannot be empty..
        /// </summary>
        public static string LASTNAME_EMPTY {
            get {
                return ResourceManager.GetString("LASTNAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name should have between 2 and 30 characters..
        /// </summary>
        public static string LASTNAME_LENGTH {
            get {
                return ResourceManager.GetString("LASTNAME_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password invalid..
        /// </summary>
        public static string LOGIN_INVALID {
            get {
                return ResourceManager.GetString("LOGIN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple type transactions defined on recurrence should have more at least 2 occurrences..
        /// </summary>
        public static string MULTIPLE_RECURRENCE_INVALID {
            get {
                return ResourceManager.GetString("MULTIPLE_RECURRENCE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters long and include at least one uppercase letter, one lowercase letter, and one special character..
        /// </summary>
        public static string PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t register more than 100 occurrences for a transaction..
        /// </summary>
        public static string RECURRENCE_OCCURRENCIES_MAX {
            get {
                return ResourceManager.GetString("RECURRENCE_OCCURRENCIES_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid recrrence type..
        /// </summary>
        public static string RECURRENCE_TYPE_INVALID {
            get {
                return ResourceManager.GetString("RECURRENCE_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single type transactions defined on recurrence should have 1 occurrence;.
        /// </summary>
        public static string SINGLE_RECURRENCE_INVALID {
            get {
                return ResourceManager.GetString("SINGLE_RECURRENCE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount should be greater than zero..
        /// </summary>
        public static string TRANSACTION_AMOUNT_INVALID {
            get {
                return ResourceManager.GetString("TRANSACTION_AMOUNT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transaction type..
        /// </summary>
        public static string TRANSACTION_TYPE_INVALID {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow error..
        /// </summary>
        public static string UNKNOW_ERROR {
            get {
                return ResourceManager.GetString("UNKNOW_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User identifier on request was not found..
        /// </summary>
        public static string USER_INVALID {
            get {
                return ResourceManager.GetString("USER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet color invalid..
        /// </summary>
        public static string WALLET_COLOR_INVALID {
            get {
                return ResourceManager.GetString("WALLET_COLOR_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet name must have at least 2 and maximum of 20 characters..
        /// </summary>
        public static string WALLET_NAME_LENGTH {
            get {
                return ResourceManager.GetString("WALLET_NAME_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid wallet type..
        /// </summary>
        public static string WALLET_TYPE_INVALID {
            get {
                return ResourceManager.GetString("WALLET_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet don&apos;t belongs to user..
        /// </summary>
        public static string WALLET_USER_AUTHORIZATION {
            get {
                return ResourceManager.GetString("WALLET_USER_AUTHORIZATION", resourceCulture);
            }
        }
    }
}
